version: '3.9'
services:
  database:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - app-data:/var/lib/mongo/data
    env_file:
      - server/.env.database
  backend:
    build:
      context: ./server
      target: ${TARGET_ENV}
      dockerfile: ./Dockerfile
    container_name: magic_backend
    env_file:
      - server/.env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - database
    restart: unless-stopped
    networks:
      - app-network
  frontend:
    build: ./client
    container_name: magic-frontend
    env_file:
      - client/.env
    ports:
      - 3000:80
    networks:
      - app-network
volumes:
  app-data:
networks:
  app-network:
