version: '3.9'
services:
  redis-server:
    image: 'redis:alpine'
    container_name: redis-ws-adapter
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
    - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - server/.env.redis
    networks:
      - app-network
  database:
    image: mongo:latest
    container_name: magic_database
    ports:
      - "27017:27017"
    volumes:
      - app-data:/var/lib/mongo/data
    env_file:
      - server/.env.database
    networks:
      - app-network
  backend:
    build:
      context: ./server
      target: ${TARGET_ENV}
      dockerfile: ./Dockerfile
    container_name: magic_backend
    tty: true
    env_file:
      - server/.env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - "9230:9230"
    depends_on:
      - database
      - redis-server
    restart: unless-stopped
    networks:
      - app-network
  frontend:
    build: ./client
    container_name: magic-frontend
    env_file:
      - client/.env
    ports:
      - "3000:80"
    networks:
      - app-network
volumes:
  app-data:
networks:
  app-network:
