// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  action: string;
  button: string;
  error: string;
  input: string;
  inputsWrapper: string;
  regForm: string;
  returnButton: string;
  root: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
